### ISSUE TITLE
Fatal Error When cURL not installed

### ISSUE THREAD

**Issue by blueliquiddesigns** [GravityPDF/gravity-forms-pdf-extended#9]
Gravity PDF 4.0-Beta:

```
Fatal error: Uncaught exception 'LogicException' with message 'The curl extension is needed to use the LogglyHandler' in /var/www/mysite/wp-content/plugins/gravity-forms-pdf-extended/vendor/monolog/monolog/src/Monolog/Handler/LogglyHandler.php:37 Stack trace: #0 /var/www/mysite/wp-content/plugins/gravity-forms-pdf-extended/src/bootstrap.php(285): Monolog\Handler\LogglyHandler->__construct('8ad317ed-213d-4...', 200) #1 /var/www/mysite/wp-content/plugins/gravity-forms-pdf-extended/src/bootstrap.php(227): GFPDF\Router->maybe_run_remote_logging() #2 /var/www/mysite/wp-content/plugins/gravity-forms-pdf-extended/src/bootstrap.php(129): GFPDF\Router->setup_logger() #3 /var/www/mysite/wp-content/plugins/gravity-forms-pdf-extended/src/depreciated.php(81): GFPDF\Router->init() #4 /var/www/mysite/wp-content/plugins/gravity-forms-pdf-extended/src/bootstrap.php(710): GFPDF_Core->__construct() #5 /var/www/mysite/wp-content/plugins/gravity-forms-pdf-extended/pdf.php(152): require_once('/var/www/recrui...') #6 [internal function]: GFPDF_ in /var/www/mysite/wp-content/plugins/gravity-forms-pdf-extended/vendor/monolog/monolog/src/Monolog/Handler/LogglyHandler.php on line 37
```

**Comment by tareqhi** [comment]
how to fix it on my site where cURL not installed?
